### ISSUE TITLE
Create way to save output as CSV instead of Parquet

### ISSUE THREAD

**Issue by Greatest125** [USEPA/standardizedinventories#113]
Firstly, this is some amazing software. Thank you for creating and actively developing it. 

Working with the Parquet file format can be a hurdle for some users, can there be an option that might save the Parquet to a CSV? 

Thank you!

**Comment by bl-young** [comment]
any dataframe can be saved as csv using [standard pandas functions](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html).

```
import stewi
inventory = 'NEI'
year = '2017'
inventory_results = stewi.getInventory(inventory,year, 'flowbyfacility')
inventory_results.to_csv('my_file.csv')
