### ISSUE TITLE
Server not compatible with RFC 5746 secure renegotiation

### ISSUE THREAD

**Issue by vlahm** [USEPA/standardizedinventories#119]
I realize this isn't the ideal place to raise such an issue, but maybe you can pass it on to the relevant parties. Modern SSL clients expect servers to adhere to [this proposed TLS standard](https://www.rfc-editor.org/info/rfc5746) which prevents a specific type of MitM attack. Attempting to use facilitymatcher with OpenSSL3 results in the following error:
```
SSLError: HTTPSConnectionPool(host='ofmext.epa.gov', port=443): Max retries exceeded with url: /FLA/www3/state_files/national_combined.zip (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)
```
I received this error by running `facilitymatches = facilitymatcher.get_matches_for_inventories(["TRI"])` on Ubuntu 20.04, under Python 3.10.5. More information can be found [here](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled).

**Comment by WesIngwersen** [comment]
URL is specified here:
https://github.com/USEPA/standardizedinventories/blob/cc026650f46fcd6a3c783b1d6798502fc92d2d40/facilitymatcher/config.yaml#L3

that is valid.

**Comment by WesIngwersen** [comment]
I'm getting a 
`zipfile.BadZipFile: File is not a zip file` error, likely because the request is not returning a valid result

**Comment by a-w-beck** [comment]
Also just found [this thread](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1963834), which I think sums up why it fails on Ubuntu 20.04.

@WesIngwersen probably worth asking the server admin if there's a path to incorporating the aforementioned TSL standard.

**Comment by WesIngwersen** [comment]
@a-w-beck Yes, please try to follow-up with them in email (cc: me)

**Comment by bl-young** [comment]
EPA alerted on 8/29.
