### ISSUE TITLE
Comparison with GHGRP flight tool, we find 2 facilities missing

### ISSUE THREAD

**Issue by TJTapajyoti** [USEPA/standardizedinventories#124]
These two facilities are missing from the STEWI generated facility file for GHGRP 2017. I have highlighted the GHGRP ID and Facility ID. 

REPORTING YEAR	FACILITY NAME	GHGRP ID	REPORTED ADDRESS	LATITUDE	LONGITUDE	CITY NAME	COUNTY NAME	STATE	ZIP CODE	PARENT COMPANIES	GHG QUANTITY (METRIC TONS CO2e)	SUBPARTS	FRSID

2017	Alamo San Antonio Cement Plant	**1007208**	6055 West Green Mountain Road	29.610148	-98.367792	San Antonio	BEXAR COUNTY	TX	78266	ALAMO CEMENT CO (100%)	**807287**	H

2017	Argos Puerto Rico, Corp.	**1006164**	Road PR-2, Km 26.7	18.3944	-66.2976	Dorado	DORADO MUNICIPIO	PR	646	ESSROC CEMENT CO (100%)	**116460**	C,H

**Comment by TJTapajyoti** [comment]
https://ghgdata.epa.gov/ghgp/main.do#/facility/?q=Find%20a%20Facility%20or%20Location&st=&bs=&et=&fid=&sf=11001100&lowE=-20000&highE=23000000&g1=1&g2=1&g3=1&g4=1&g5=1&g6=0&g7=1&g8=1&g9=1&g10=1&g11=1&g12=1&s1=0&s2=0&s3=0&s4=1&s5=0&s6=0&s7=0&s8=0&s9=0&s10=0&s201=0&s202=0&s203=0&s204=0&s301=0&s302=0&s303=0&s304=0&s305=0&s306=0&s307=0&s401=1&s402=0&s403=0&s404=0&s405=0&s601=0&s602=0&s701=0&s702=0&s703=0&s704=0&s705=0&s706=0&s707=0&s708=0&s709=0&s710=0&s711=0&s801=0&s802=0&s803=0&s804=0&s805=0&s806=0&s807=0&s808=0&s809=0&s810=0&s901=0&s902=0&s903=0&s904=0&s905=0&s906=0&s907=0&s908=0&s909=0&s910=0&s911=0&si=&ss=&so=0&ds=E&yr=2017&tr=current&cyr=2020&ol=0&sl=0&rs=ALL

**Comment by WesIngwersen** [comment]
@TJTapajyoti is there a reason that you closed this? are those facilities actually present?
