### ISSUE TITLE
v.1.0.5  SteWI issue with Posix path. While the solution seems simple str() but this issue cropped up recently. 

### ISSUE THREAD

**Issue by tjlca** [USEPA/standardizedinventories#138]
File "/Users/tghosh/Box Sync/FECM inventory/Industrial-Emissions-Inventory_2011/fecm_data_explorationv2.py", line 23, in <module>
    import stewi,stewicombo
  File "/Users/tghosh/Box Sync/FECM inventory/Industrial-Emissions-Inventory_2011/standardizedinventories-1.0.5/stewi/__init__.py", line 10, in <module>
    from stewi.globals import log, add_missing_fields,\
  File "/Users/tghosh/Box Sync/FECM inventory/Industrial-Emissions-Inventory_2011/standardizedinventories-1.0.5/stewi/globals.py", line 43, in <module>
    paths.local_path = os.path.realpath(paths.local_path + "/stewi")
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

**Comment by tjlca** [comment]
Is this because of esupy update? I updated the posix path issue locations with str() and finally was stuck with an esupy error.

**Comment by bl-young** [comment]
All current release of StEWI (< = 1.0.6) need to use esupy <= 0.2.2.

If you updated esupy from develop, but not stewi than you are likely to run into an error.

If you use the current master of both (1.0.6, and 0.2.2) I don't believe you will get this error.

**Comment by bl-young** [comment]
Note the requirements of v 1.0.6:

https://github.com/USEPA/standardizedinventories/blob/70158b16c42eb78eb81751f0882663d3149f5a30/setup.py#L3

**Comment by tjlca** [comment]
```
install_requires=['esupy @ git+https://github.com/USEPA/esupy#egg=esupy',
                  'numpy>=1.20.1',
                  'pandas>=1.3',
                  'requests>=2.20',
                  'beautifulsoup4>=4.9.3',
                  'PyYAML>=5.1',
                  'openpyxl>=3.0.7',
                  'xlrd>=2.0.0',
                  ]
```


StEWI v1.0.5 setup file misses the parameter asking for esupy version 0.2.2 which results in all previous versions of StEWI not working any more. Could you kindly add the line 

`'esupy @ git+https://github.com/USEPA/esupy@v0.2.2#egg=esupy',`

in the setup files of the previous versions? 

The issue is resolved by this solution.
