### ISSUE TITLE
Which facilitymatcher to use?

### ISSUE THREAD

**Issue by dt-woods** [USEPA/standardizedinventories#163]
I'm noticing that [facilitymatcher](https://github.com/USEPA/facilitymatcher/) code appears reproduced here under the submodule of the same name. Are both being updated? Is one to be used in preference over the other?

**Comment by bl-young** [comment]
No, the facilitymatcher is a submodule of this repo, the one you link to is old.

**Comment by bl-young** [comment]
@WesIngwersen can we delete that repository or archive it?

If not, perhaps it should have a substantial warning at the top of the readme that it is not up to date.
