### ISSUE TITLE
Missing parameter in download_extract_FRS_combined_national

### ISSUE THREAD

**Issue by gschivley** [USEPA/standardizedinventories#18]
This function requires 1 parameter (FRSpath) but is called without any inputs.

https://github.com/USEPA/standardizedinventories/blob/b0fdd212ae5420233d2f0c0ecb2aac1745e87da9/facilitymatcher/WriteFacilityMatchesforStEWI.py#L19

**Comment by WesIngwersen** [comment]
Fixed by this [commit](https://github.com/USEPA/standardizedinventories/commit/0bb45d37eb3b5aa27a3847b609d3b6f271d7be46)
