### ISSUE TITLE
stewicombo - duplicates when facility has more than one FRS ID

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/standardizedinventories#24]
found by @TJTapajyoti 
inventories_of_interest ={'eGRID': 2016, 'TRI': 2016, 'NEI': 2016, 'RCRAInfo': 2015}
emissions_and_wastes_by_facility = stewicombo.combineInventoriesforFacilitiesinOneInventory("eGRID",inventories_of_interest,filter_for_LCI=True)

returns duplicates like this

|FRS_ID|FacilityID|FlowAmount|FlowName|Source|
|---|---|---|---|---|
|110001536197|10123|1006345.47519044|Carbon dioxide|eGRID|
|110017313423|10123|1006345.47519044|Carbon dioxide|eGRID|

**Comment by bl-young** [comment]
resolved with https://github.com/USEPA/standardizedinventories/commit/1e77959d93c11cfaa4a6afe6b73f6d5de3662e47
