### ISSUE TITLE
TRI - Dioxin flows not validating

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/standardizedinventories#29]
Reviewing some random validation files, the stewi produced Dioxin flows are much different than the validation source

**Comment by bl-young** [comment]
Dioxins are listed twice (first in lbs, then in grams)
https://github.com/USEPA/standardizedinventories/blob/master/stewi/data/TRI_chem_release_2015.csv#L237
https://github.com/USEPA/standardizedinventories/blob/master/stewi/data/TRI_chem_release_2015.csv#L501

This will be resolved in upcoming pull request

**Comment by bl-young** [comment]
resolved by https://github.com/USEPA/standardizedinventories/commit/56504773e9ffdb53f5d5a074d1d968672153968a. Additional years still need to be processed.
