### ISSUE TITLE
config.yaml is not being included when installing

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/standardizedinventories#30]
Receive error:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/jamiesom/AppData/Roaming/Python/Python37/site-packages/chemicalmatcher/config.yaml'`
After installing electricitylci via pip. I suspect the package data for setup.py here needs to be modified to include the file.

**Comment by WesIngwersen** [comment]
Causing [electricitylci main to fail](https://github.com/USEPA/ElectricityLCI/issues/102)

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt yes i suspect you are right that we need to specifiy those config.yaml files in the setup..the one in stewi is getting installed but there is also one missing in facilitymatcher

**Comment by WesIngwersen** [comment]
After addition to package data in setup of the two files i confirmed they do get installed when installing from pip into the site-packages
