### ISSUE TITLE
Speed up stewicombo

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/standardizedinventories#31]
Reported by @gschivley 
I did some line profiling (%lprun magic)
and most of the time is in just a few places.
The function aggregate_and_remove_overlap(inventories) takes 99.7% of the time
Within aggregate_and_remove_overlap(), 62% of time is spent on line 111 (df_new =
grouped_by_src.agg(func_cols_map))
31% is on line 115 (df_new = grouped.apply(get_by_preference)).
I don't have a clear picture in my head of what's happening through the whole process but
I'm attaching the lprun results, broken out by a few of the functions.
Most of the time is spent on line 111 of aggregate_and_remove_overlap (original line number
- I'm attaching a second set of lprun results with 2 new lines at 108/9). func_cols_map is a
dictionary with functions to apply to each column. One of the functions is get_first_item,
which uses .iloc[0] to select the first row of the column. This is relatively slow and can be
replaced with the built-in pandas method .first(). To implement in the aggregate method you
only need to assign the string "first" as the value for the each key in func_cols_map. The
.first() method is around 50x faster than iloc[0], and shaves a couple min off the total time.
You can see my change in lines 108/9.
How to interpret the lprun results:
Each function profiled has a "Total time" at the top, the number of time each line is run,
the time per line (total), time per hit, and % of time on each line within that function.
The results below are for the function get_by_preference, used in a groupby().apply() on
line 115 of overlaphandler.py.
55.5 seconds are spend within this function.
91% of the time is spent iterating through the rows of each group.
I might be missing something here but slicing the dataframes is probably much
faster than iterating over rows.
Total time: 55.5582 s
File: /Users/standardizedinventories/
stewicombo/overlaphandler.py
Function: get_by_preference at line 36

|Line| Hits| Time| Per Hit| % Time| Line Contents|
|---|---|---|---|---|---|
|37|58570|130121.0|2.2|0.2|preferences = INVENTORY_PREFERENCE_BY_COMPARTMENT[group.name]|
|39|119678|98851.0|0.8|0.2| for pref in preferences:|
|40|180786|50576395.0|279.8|91.0| for index, row in group.iterrows():|
|41|119678|4543449.0|38.0|8.2|if pref == row[SOURCE_COL]:|
|42|58570|209420.0|3.6|0.4|return row|

What's important to note here is that while 55 seconds are spent within the function, 261
seconds are spent on line 115 (again, these times are just for eGRID and TRI). So ~80% of the
time seems to be spent overhead apply the function. Figuring out a way to achieve the same
goal without the apply - maybe by slicing rather than using groupby - could save even more
time.

113 comment If we have 2 or more duplicates with same compartment use
`INVENTORY_PREFERENCE_BY_COMPARTMENT`

|Line| Hits| Time| Per Hit| % Time| Line Contents|
|---|---|---|---|---|---|
|114|29285|10662992.0|364.1|1.3|grouped =df_new.groupby(COMPARTMENT_COL)|
|115|29285|261084505.0|8915.3|30.8|df_new =grouped.apply(get_by_preference)|   
     
And finally, since there are so many loops over grouped items, it might be worth trying
to parallelize the code. It's pretty easy with joblib.

**Comment by bl-young** [comment]
Speed for running overlaph handler is much faster. Marking as closed.
