### ISSUE TITLE
Flow by facility output data does not match format specs

### ISSUE THREAD

**Issue by bl-young** [USEPA/standardizedinventories#32]
Compare: [FlowByFacility.MD](https://github.com/USEPA/standardizedinventories/blob/master/format%20specs/FlowByFacility.md)
with an output file like: [TRI_2018.csv](https://github.com/USEPA/standardizedinventories/blob/master/stewi/output/flowbyfacility/TRI_2018.csv)

**Comment by WesIngwersen** [comment]
@bl-young 
It looks right to me except it's missing Unit which actually was added later.  So Unit could be added.
The order doesn't have to match - it's not important

pasted from the top of the TRI_2018 csv
FacilityID,FlowName,Compartment,FlowAmount,ReliabilityScore

**Comment by bl-young** [comment]
Ok we will update with units when we do NEI

**Comment by WesIngwersen** [comment]
@bl-young Let me qualify this. In the stored csv file, units are missing. But the stewi call will return the units column. See [this line](https://github.com/USEPA/standardizedinventories/blob/19cb340a43a98b46db6560a6b04f6104ce39e7af/stewi/__init__.py#L71) in getInventory() that tacks units on. The reasoning here is that csvs take a lot of storage space and the whole column is just a common value. Closing out this issue
