### ISSUE TITLE
Refactor NEI.py to function like TRI/RCRAInfo

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/standardizedinventories#35]
NEI.py would ideally function now like the recently refactored TRI.py and RCRAInfo.py, with a main function that gets parameters with argparse for year and other options.  The code now requires a code update to run a different year which is not ideal.

**Comment by WesIngwersen** [comment]
@bl-young Let me know if you guys can work on this

**Comment by bl-young** [comment]
Absolutely, yes. That's the plan. Wanted to get a functioning update in there before refactoring. @ericmbell1
